spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cerveceriaDB
    username: root
    password: 120383..
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9090